---
title: "Assignment 11b - HTML Tables Submit Assignment"
author: "Damilare Olaleye"
date: "11/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PART 1

The webpage http://www.goodcarbadcar.net/2017/01/usa-2016-auto-brand-sales-results-rankings/ (Links to an external site.) contains car sales for 2016 and 2015 for the major automakers.

1.  Collect the 2016 and 2015 sales for five manufacturers.

2015,2016 : Mazda, Infiniti, Lexus, Fiat, Subaru

2.  Create a html page containing (1) a sentence or two sentences introducing the data, and (2) a single html table with this sales data for the five manufacturers.  (Your table will have six rows and three columns.)  Make sure that this html page displays fine using a web browser.



3.  Upload your html page to your personal website.

4.  Read your html page into R.  

5.  Using character manipulation commands, get the data from your html page into a data frame.  Display your data frame to make sure that it contains clean data.

6.  Compute the percentage increase in sales for your five manufacturers.

7.  Using ggplot, construct a graph where the manufacturer names are on the vertical scale and the percentage increases on the horizontal scale.

PART 2

1.  Find a “top-10” table on a html page.  Read this html page into R.

2.  Using character manipulation functions, create a data frame with this top-10 information.

3.  Construct a good graph of this top-10 data.